---

- name: Get packages
  ansible.builtin.set_fact:
    postgresql_packages: >-
      {%- if postgresql_install_type == 'server' -%}
      {{ postgresql_server_packages }}
      {%- else -%}
      {{ postgresql_client_packages }}
      {%- endif -%}

- name: Show packages
  ansible.builtin.debug:
    msg:
      postgresql_packages: "{{ postgresql_packages }}"

- name: Setup-repository RedHat
  when: ansible_os_family == 'RedHat'
  block:

    - name: Import RPM signing key
      ansible.builtin.rpm_key:
        key: "{{ postgresql_gpg_key }}"
        state: present
      environment:
        HTTPS_PROXY: "{{ postgresql_proxy | default('') }}"
        HTTP_PROXY: "{{ postgresql_proxy | default('') }}"

    - name: Disable the built-in PostgreSQL module
      ansible.builtin.command:
        cmd: dnf -qy module disable postgresql
      changed_when: false
      failed_when: _postgresql.rc > 1
      register: _postgresql
      when: ansible_distribution_major_version | int >= 8

    - name: Setup yum/dnf repository
      ansible.builtin.yum_repository:
        name: postgresql-{{ postgresql_version }}
        description: PostgresSQL {{ postgresql_version }}
        file: postgresql.repo
        baseurl: "{{ postgresql_repo }}"
        gpgcheck: yes
        enabled: no
        proxy: "{{ postgresql_proxy | default('') }}"

    - name: Install postgresql required packages
      ansible.builtin.yum:
        name: "{{ postgresql_packages }}"
        state: "{{ postgresql_package_state | default('present') }}"
        enablerepo: "postgresql-{{ postgresql_version }}"

    - name: Install postgresql optional packages
      ansible.builtin.yum:
        name: "{{ postgresql_optional_packages }}"
        state: "{{ postgresql_package_state | default('present') }}"
        enablerepo: "postgresql-{{ postgresql_version }}"
      when: postgresql_install_optional_packages | bool


- name: Setup-repository Debian
  when: ansible_os_family == 'Debian'
  block:

    - name: Install GPG
      ansible.builtin.apt:
        name: gnupg
        state: present

    - name: Import APT key from official PostgreSQL repository (Debian)
      ansible.builtin.apt_key:
        url: "{{ postgresql_gpg_key }}"

    - name: Add official PostgreSQL repository (Debian)
      ansible.builtin.apt_repository:
        repo: deb {{ postgresql_repo }} {{ ansible_distribution_release }}-pgdg main
        filename: "pgdg.list"
        state: present
      register: _apt_repo

    - name: Update package list (APT)  # noqa no-handler
      ansible.builtin.apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0
      when: _apt_repo.changed

    - name: Install postgresql required OS packages
      ansible.builtin.apt:
        name: "{{ postgresql_packages }}"
        state: "{{ postgresql_package_state | default('present') }}"

    - name: Install postgresql optional OS packages
      ansible.builtin.apt:
        name: "{{ postgresql_optional_packages }}"
        state: "{{ postgresql_package_state | default('present') }}"
      when: postgresql_install_optional_packages | bool

- name: Install postgresql pypi packages
  ansible.builtin.pip:
    name: "{{ postgresql_pip_packages }}"
    state: present
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ postgresql_bin_dir }}"
