---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    postgresql_db_name: test
    postgresql_db_user: test
    postgresql_db_password: test
  tasks:

    - name: Install postgresql client
      ansible.builtin.include_role:
        name: ansible-role-postgresql
      vars:
        postgresql_install_type: client

    - name: Install postgresql server
      ansible.builtin.include_role:
        name: ansible-role-postgresql
      vars:
        postgresql_install_type: server
